name: Sync Element Web

on:
  schedule:
    - cron: "0 3 * * 1"  # every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest release info
        id: release
        run: |
          LATEST=$(curl -s https://api.github.com/repos/element-hq/element-web/releases/latest | jq -r '.tag_name')
          echo "tag=$LATEST" >> $GITHUB_OUTPUT

      - name: Download release tarball
        run: |
          curl -L https://github.com/element-hq/element-web/archive/refs/tags/${{ steps.release.outputs.tag }}.tar.gz \
            -o element-web.tar.gz
          tar -xzf element-web.tar.gz
          mv element-web-* upstream-release

      - name: Run custom script
        run: |
          chmod +x ./scripts/rename.sh
          ./scripts/rename.sh ./upstream-release ./processed

      - name: Commit and push changes
        run: |
          rsync -a --delete --exclude='.github' --exclude='scripts' ./processed/ ./
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update to ${{ steps.release.outputs.tag }}" || echo "No changes to commit"
          git push origin main

      - name: Notify via issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "New Element Web release ${{ steps.release.outputs.tag }}"
          content-filepath: ./processed/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
